POST  https://powerful-anchorage-21815.herokuapp.com/login
Content-Type: application/json

{
    "Email":"amit@amit.com",
    "password":"amitamit"
}

GET https://powerful-anchorage-21815.herokuapp.com/resources
Content-Type: application/json
{
    
}